### ISSUE TITLE
regex support

### ISSUE THREAD

**Issue by YangGuofu** [kwaschny/TaskBarRenamer#1]
![image](https://github.com/kwaschny/TaskBarRenamer/assets/30237908/dc82e34d-e9db-4cfd-b2b0-f4c9dd51a3a1)

Can you support regex to it, like "game-admin*"

**Comment by kwaschny** [comment]
Sure. Regex and simple wildcard patterns shouldn't be a problem.

**Comment by kwaschny** [comment]
Implemented via 003a9007718d49b52728b692edd69738998b1610 and [released with 0.4](https://github.com/kwaschny/TaskBarRenamer/releases/tag/0.4).

**Comment by YangGuofu** [comment]
> Implemented

Thanks for the quick responses!
