### ISSUE TITLE
The order of open windows' name in taskbar is wrong

### ISSUE THREAD

**Issue by cruisermaxx** [kwaschny/TaskBarRenamer#2]
Dear developer, the order of open windows' name in taskbar is unconsistance with the actual order.
Is there any way to fix this problem?

**Comment by kwaschny** [comment]
Can you please elaborate what you mean by windows order?

**Comment by cruisermaxx** [comment]
> Can you please elaborate what you mean by windows order?

Thank you very much for replying! Sure, I found the windows order in taskbar is actually the reverse order of the list in RaskBarRenamer. So this function works well now. I misunderstood the list order before.
Thank you for the software.
